
title: "Explorando el mundo financiero"
subtitle: "Blog Personal"
name: "José Franco Chalco"
email: "josefrancochalco@gmail.com"
description: "Blog personal sobre finanzas, programación, economía y todo lo que existe en el medio."
baseurl: ""
domain: JoseFrancoCh.github.io
url: https://JoseFrancoCh.github.io
github_username: JoseFrancoCh

logo: "/assets/logo/logo.png"

locale: "es-ES"
search: true
#timezone: "America/Santiago"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed

# Site Author
author:
  name     : "José Franco Chalco"
  bio      : "Ingeniero Financiero con mas de 10 años de experiencia."
  location : "Chile"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:josefrancochlco@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JoseFrancoCh"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JoseFrancoCh"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jose-franco-chalco-frm-3911a52a"

atom_feed:
  hide: true

collections:
  finanzas:
    output: true
    permalink: /:collection/:path/
  programacion:
    output: true
    permalink: /:collection/:path/
  cheat_sheets:
    output: true
    permalink: /:collection/:path/
    order:
      - calculo.md
      - calculo_multivariado.md
      - estadistica.md
      - calculo_estocastico.md
      - python.md
      - cplus.md
      - swift.md
      - javascript.md
      - git.md
      - latex.md
      - django.md
      - bootstrap.md
      - jekyll.md
      - apache.md
      - postgresql.md
      - sql_server.md
      - pycharm.md
      - vscode.md
      - xcode.md

defaults:
  # Cheat Sheets
  - scope:
      path: ""
      type: cheat_sheets
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "cheat_sheets"
      toc: True
      toc_label: Secciones

